apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.image-pull-policy: Never
    kompose.service.type: nodeport
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.image-pull-policy: Never
        kompose.service.type: nodeport
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: api
    spec:
      containers:
        - env:
            - name: MONGO_CONNECTION_STRING
              value: mongodb://mongodb_user:mongodb_password@db:27017/mondogb?authSource=admin
          image: api
          imagePullPolicy: Never
          name: api
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
