services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      MONGO_CONNECTION_STRING: mongodb://mongodb_user:mongodb_password@db:27017/mondogb?authSource=admin
    labels:
      kompose.service.type: nodeport
      kompose.image-pull-policy: Never
    networks:
      - app-network

  db:
    image: mongo:7
    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_DATABASE: mondogb
      MONGO_INITDB_ROOT_USERNAME: mongodb_user
      MONGO_INITDB_ROOT_PASSWORD: mongodb_password
    volumes:
      - ./mongo-data:/data/db
    restart: always
    networks:
      - app-network

  web:
    build: ./web
    ports:
      - "8081:80"
    labels:
      kompose.service.type: LoadBalancer
      kompose.service.expose: true
      kompose.image-pull-policy: Never
    environment:
      API_URL: http://api:8080
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
