apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.image-pull-policy: Never
    kompose.service.expose: "true"
    kompose.service.type: LoadBalancer
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.image-pull-policy: Never
        kompose.service.expose: "true"
        kompose.service.type: LoadBalancer
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: web
    spec:
      containers:
        - env:
            - name: API_URL
              value: http://api:8080
          image: web
          imagePullPolicy: Never
          name: web
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
